name: Deploy EnlaceCRM dashboard en servidor windows automatico

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Clonar repositorio en la ruta destino
        shell: powershell
        run: |
          $destino = "C:\EnlaceCRM\EnlaceCRM_dashboard"
          if (Test-Path $destino) {
            Set-Location $destino
            git fetch --all
            git reset --hard origin/main
          }

      - name: Instalar dependencias
        shell: powershell
        run: |
          Set-Location "C:\EnlaceCRM\EnlaceCRM_dashboard"
          npm install

      - name: Compilar Vue app
        shell: powershell
        run: |
          Set-Location "C:\EnlaceCRM\EnlaceCRM_dashboard"
          npm run build

      - name: Copiar archivos compilados a ruta de Nginx
        shell: powershell
        run: |
          $origen = "C:\EnlaceCRM\EnlaceCRM_dashboard\dist"
          $destino = "C:\Nginx\html\EnlaceCRM_dashboard"
          if (Test-Path $destino) {
            Remove-Item -Recurse -Force "$destino\*"
          } else {
            New-Item -ItemType Directory -Path $destino | Out-Null
          }
          Copy-Item -Path "$origen\*" -Destination $destino -Recurse

      - name: Reiniciar Nginx
        shell: powershell
        run: |
          Set-Location "C:\Nginx\nginx-1.28.0"
          .\nginx.exe -s reload
