name: Deploy EnlaceCRM dashboard en servidor windows automatico 

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Instalar dependencias
        run: npm install

      - name: Compilar Vue app
        run: npm run build

      - name: Reiniciar Nginx
        shell: powershell
        run: |
          taskkill /F /IM nginx.exe
          Start-Sleep -Seconds 2
          Start-Process "C:\Nginx\nginx-1.28.0\nginx.exe"
